version: 2
dependencies:
  pre:
    - sudo yum update
    - sudo yum install libunwind libicu
    - sudo yum install dotnet-sdk-2.1.4
  override:
    - dotnet restore

test:
  pre:
    - dotnet --version
    - dotnet pack

