version: 2
dependencies:
  pre:
    - sudo yum update
    - sudo yum install libunwind libicu
    - sudo yum install dotnet-sdk-2.1.4
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Start building a sample dotnet core project.
      - run:
          name: Print the Current Time
          command: date
      - run:
        name: dotnet pack

